version: '3.9'

services:

  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3307

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-app
    depends_on:
      - mysqldb
    links:
      - "mysqldb:todo_express"
    stdin_open: true
    tty: true
    ports:
      - 3000:3000

networks:
  default:
    # Use a custom driver
    external: true
    name: node-app

volumes: 
  db-config:
  db-data: